name: CI: Integration, Dependency Check, UI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker-compose -f nginx-proxy/nginx-compose.yml up -d
          sleep 10

      - name: UI Test - Check index.html loads
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost | grep 200

  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "SecureWebApp"
          path: "."
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: dependency-check-report
